name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'windows', image: 'windows-latest' },
          ]

    runs-on: ${{ matrix.os.image }}

    steps:
    - uses: actions/checkout@v3
    - name: Download
      id: download
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "Painkiller1991/QueueClient"
        latest: true
        fileName: "*"
        token: ${{ secrets.QUEUECLIENT }}
    - name: Publish
      id: upload-release-asset 
      uses: Fhwang0926/upload-release-asset@v1.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.download.outputs.upload_url  }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_name: ./*.exe # path + filename
        asset_label: latest
      
