name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'windows', image: 'windows-latest' },
          ]

    runs-on: ${{ matrix.os.image }}

    steps:
    - uses: actions/checkout@v3
    - name: Download
      id: download
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "Painkiller1991/QueueClient"
        latest: true
        fileName: "*"
        token: ${{ secrets.QUEUECLIENT }}
    - name: Publish
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "${{ steps.download.outputs.upload_url }}"
        tags: false
        draft: false
      
