name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'windows', image: 'windows-latest' },
          ]

    runs-on: ${{ matrix.os.image }}

    steps:
    - uses: actions/checkout@v3
    - name: Upload binaries to release
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "Painkiller1991/QueueClient"
        latest: true
        fileName: "*"
        token: ${{ secrets.QUEUECLIENT }}
