name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'windows', image: 'windows-latest' },
          ]

    runs-on: ${{ matrix.os.image }}

    steps:
    - uses: actions/checkout@v3
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: Painkiller1991/QueueClient
        # A personal access token for the GitHub repository in which the release will be created and edited.
        # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
        repo_token: ${{ secrets.QUEUECLIENT }}
        file: queueclient*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
